server:
  port: 8010

spring:
  datasource:
    read:
      url: jdbc:oracle:thin:@x.x.x.x:1521/xxxxxxxxx
      driver-class-name: oracle.jdbc.OracleDriver
      username: *******
      password: *******
    readWrite:
      url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS SCHEMA_USERS;NON_KEYWORDS=KEY
      driver-class-name: org.h2.Driver
      username: sa
      password:

  jpa:
    show-sql: true

  sql:
    init:
      data-locations:
        - classpath:data-h2.sql
 #----------- allowed cors origin
cors:
  allowed-origins:
    - http://localhost:3000